# Explanations for customers who are predicted to CHURN (Leave)
CHURN_REASONS = {
    "tenure": "Short tenure period (ඉතා කෙටි කාලයක් පමණක් සමාගම සමඟ රැඳී සිටීම)",
    "TenureInYears": "Short tenure period (ඉතා කෙටි කාලයක් පමණක් සමාගම සමඟ රැඳී සිටීම)",
    "MonthlyCharges": "High monthly charges (මාසික ගාස්තුව ඉතා ඉහළ වීම)",
    "TotalCharges": "Low total charges reflecting a short stay (මේ දක්වා ගෙවා ඇති මුළු මුදල අඩු වීම)",
    "gender": "Gender factor (ස්ත්‍රී/පුරුෂ භාවය මත පදනම් වූ සාධකයක්)",
    "SeniorCitizen": "Being a Senior Citizen (වැඩිහිටි පුරවැසියෙකු වීම)",
    "Partner": "Living without a partner (සහකරුවෙකු නොමැති වීම)",
    "Dependents": "Having no dependents (යැපෙන්නන් නොමැති වීම)",
    "PhoneService": "Lack of phone service (දුරකථන සේවාවක් නොමැති වීම)",
    "PaperlessBilling": "Uses paperless billing which makes it easier to switch (විද්‍යුත් බිල්පත් භාවිතය නිසා පහසුවෙන් වෙනත් සේවාවකට මාරු විය හැකි වීම)",
    "MultipleLines_No phone service": "No phone service (දුරකථන සේවාවක් නොමැති වීම)",
    "MultipleLines_Yes": "High cost of maintaining multiple lines (දුරකථන මාර්ග කිහිපයක් සඳහා වැය වන ඉහළ පිරිවැය)",
    "InternetService_Fiber optic": "Issues or costs related to Fiber optic internet (ෆයිබර් ඔප්ටික් අන්තර්ජාල සේවාවේ පිරිවැය හෝ ගැටලු)",
    "InternetService_No": "Lack of internet service (අන්තර්ජාල සේවාවක් නොමැති වීම)",
    "OnlineSecurity_No internet service": "Lack of internet service (අන්තර්ජාල සේවාවක් නොමැති වීම)",
    "OnlineSecurity_Yes": "Additional cost for online security (මාර්ගගත ආරක්ෂණ සේවාව සඳහා වන අමතර පිරිවැය)",
    "OnlineBackup_No internet service": "Lack of internet service (අන්තර්ජාල සේවාවක් නොමැති වීම)",
    "OnlineBackup_Yes": "Additional cost for online backup (දත්ත උපස්ථ සේවාව සඳහා වන අමතර පිරිවැය)",
    "DeviceProtection_No internet service": "Lack of internet service (අන්තර්ජාල සේවාවක් නොමැති වීම)",
    "DeviceProtection_Yes": "Additional cost for device protection (උපාංග ආරක්ෂණ සේවාව සඳහා වන අමතර පිරිවැය)",
    "TechSupport_No internet service": "Lack of internet service (අන්තර්ජාල සේවාවක් නොමැති වීම)",
    "TechSupport_Yes": "Additional cost for tech support (තාක්ෂණික සහාය සඳහා වන අමතර පිරිවැය)",
    "StreamingTV_No internet service": "Lack of internet service (අන්තර්ජාල සේවාවක් නොමැති වීම)",
    "StreamingTV_Yes": "Additional cost for streaming TV (රූපවාහිනී සේවාව සඳහා වන අමතර පිරිවැය)",
    "StreamingMovies_No internet service": "Lack of internet service (අන්තර්ජාල සේවාවක් නොමැති වීම)",
    "StreamingMovies_Yes": "Additional cost for streaming movies (චිත්‍රපට සේවාව සඳහා වන අමතර පිරිවැය)",
    "Contract_One year": "Only bound by a short 1-year contract (වසරක කෙටිකාලීන ගිවිසුමක සිටීම)",
    "Contract_Two year": "Reaching the end of a 2-year contract (වසර දෙකක ගිවිසුම් කාලය අවසන් වෙමින් පැවතීම)",
    "PaymentMethod_Credit card (automatic)": "Credit card payment factors (ක්‍රෙඩිට් කාඩ්පත් ගෙවීම් සම්බන්ධ සාධක)",
    "PaymentMethod_Electronic check": "Issues or preferences related to Electronic check payments (ඉලෙක්ට්‍රොනික චෙක්පත් හරහා ගෙවීම් සිදු කිරීම)",
    "PaymentMethod_Mailed check": "Inconvenience of Mailed check payments (තැපැල් චෙක්පත් හරහා ගෙවීම් සිදු කිරීමේ අපහසුතා)"
}

# Explanations for customers who are predicted to STAY
STAY_REASONS = {
    "tenure": "Long loyal tenure period (දීර්ඝ කාලයක් සමාගම සමඟ රැඳී සිටීම)",
    "TenureInYears": "Long loyal tenure period (දීර්ඝ කාලයක් සමාගම සමඟ රැඳී සිටීම)",
    "MonthlyCharges": "Low and affordable monthly charges (මාසික ගාස්තුව අඩු මට්ටමක පැවතීම)",
    "TotalCharges": "High accumulated total charges showing loyalty (දීර්ඝ කාලීනව ඉහළ ගාස්තුවක් ගෙවා තිබීම)",
    "gender": "Gender factor (ස්ත්‍රී/පුරුෂ භාවය මත පදනම් වූ සාධකයක්)",
    "SeniorCitizen": "Not being a Senior Citizen (තරුණ හෝ මැදි වයසේ පාරිභෝගිකයෙකු වීම)",
    "Partner": "Having a partner (සහකරුවෙකු සිටීම)",
    "Dependents": "Having dependents or family (යැපෙන්නන් හෝ පවුලේ සාමාජිකයින් සිටීම)",
    "PhoneService": "Using the company's phone service (සමාගමේ දුරකථන සේවාව භාවිතා කිරීම)",
    "PaperlessBilling": "Using traditional paper billing (සාමාන්‍ය බිල්පත් ක්‍රමය භාවිතා කිරීම)",
    "MultipleLines_No phone service": "No additional costs for multiple lines (අමතර දුරකථන මාර්ග නොමැති වීම)",
    "MultipleLines_Yes": "Using multiple lines for family/business (පවුලේ හෝ ව්‍යාපාරික අවශ්‍යතා සඳහා මාර්ග කිහිපයක් භාවිතා කිරීම)",
    "InternetService_Fiber optic": "Satisfaction with high-speed Fiber optic internet (වේගවත් ෆයිබර් ඔප්ටික් අන්තර්ජාලය භාවිතා කිරීම)",
    "InternetService_No": "No additional costs for internet service (අන්තර්ජාල සේවාවන් භාවිතා නොකිරීම)",
    "OnlineSecurity_No internet service": "No additional costs for internet service (අන්තර්ජාල සේවාවන් භාවිතා නොකිරීම)",
    "OnlineSecurity_Yes": "Using online security features (මාර්ගගත ආරක්ෂණ සේවාවන් භාවිතා කිරීම)",
    "OnlineBackup_No internet service": "No additional costs for internet service (අන්තර්ජාල සේවාවන් භාවිතා නොකිරීම)",
    "OnlineBackup_Yes": "Using online backup services (දත්ත උපස්ථ සේවාවන් භාවිතා කිරීම)",
    "DeviceProtection_No internet service": "No additional costs for internet service (අන්තර්ජාල සේවාවන් භාවිතා නොකිරීම)",
    "DeviceProtection_Yes": "Using device protection plans (උපාංග ආරක්ෂණ සේවාවන් භාවිතා කිරීම)",
    "TechSupport_No internet service": "No additional costs for internet service (අන්තර්ජාල සේවාවන් භාවිතා නොකිරීම)",
    "TechSupport_Yes": "Receiving technical support (තාක්ෂණික සහාය ලබා ගැනීම)",
    "StreamingTV_No internet service": "No additional costs for internet service (අන්තර්ජාල සේවාවන් භාවිතා නොකිරීම)",
    "StreamingTV_Yes": "Enjoying streaming TV services (රූපවාහිනී සේවාවන් භාවිතා කිරීම)",
    "StreamingMovies_No internet service": "No additional costs for internet service (අන්තර්ජාල සේවාවන් භාවිතා නොකිරීම)",
    "StreamingMovies_Yes": "Enjoying streaming movie services (චිත්‍රපට සේවාවන් භාවිතා කිරීම)",
    "Contract_One year": "Bound by a 1-year contract (වසරක ගිවිසුමකට බැඳී සිටීම)",
    "Contract_Two year": "Bound by a 2-year long-term contract (වසර දෙකක දිගුකාලීන ගිවිසුමකට බැඳී සිටීම)",
    "PaymentMethod_Credit card (automatic)": "Using automated credit card payments (ස්වයංක්‍රීය ක්‍රෙඩිට් කාඩ්පත් ගෙවීම් භාවිතා කිරීම)",
    "PaymentMethod_Electronic check": "Using Electronic checks for payments (ඉලෙක්ට්‍රොනික චෙක්පත් හරහා ගෙවීම් සිදු කිරීම)",
    "PaymentMethod_Mailed check": "Using traditional Mailed checks (තැපැල් චෙක්පත් හරහා ගෙවීම් සිදු කිරීම)"
}